apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: brainupgrade/configmap:3
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef: 
              name: weather-config
