apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      containers:
      - name: weather
        image: brainupgrade/weather-py:3
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
          - name: DB_HOST
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: db_host
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: db_username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: db_password
          - name: DB_NAME
            valueFrom:
              secretKeyRef:
                name: weather-secret
                key: db_name
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: weather-config
                key: ENVIRONMENT
          - name: API_URL_WEATHER
            valueFrom:
              configMapKeyRef:
                name: weather-config
                key: API_URL_WEATHER
          - name: API_URL_GEOCODING
            valueFrom:
              configMapKeyRef:
                name: weather-config
                key: API_URL_GEOCODING
