apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounting-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounting
      release: "1.0"
  template:
    metadata:
      labels:
        app: accounting
        release: "1.0"
    spec:
      containers:
      - image: brainupgrade/accounting:1.0
        name: accounting
        ports:
        - containerPort: 8080
          protocol: TCP
