apiVersion: v1
kind: Service
metadata:
  name: weather-db
  namespace: weather
spec:
  type: ClusterIP
  ports:
    - name: mariadb
      port: 3306
      targetPort: 3306
  selector:
    app: weather-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-db
  namespace: weather
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-db
  template:
    metadata:
      labels:
        app: weather-db
    spec:
      containers:
      - image: mariadb:10.3
        name: mariadb
        resources: 
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi         
        ports:
        - containerPort: 3306
          name: mariadb
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: spring.datasource.password
          - name: MYSQL_DATABASE
            value: weather
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: spring.datasource.username
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: spring.datasource.password
