apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: payments-developer-binding
  namespace: payments
subjects:
- kind: User
  name: payments-developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: payments-developer
  apiGroup: rbac.authorization.k8s.io
