apiVersion: v1
kind: Pod
metadata:
  name: nginx-cache-ebs
spec:
  containers:
    - name: web-server
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - name: nginx-cache         
          mountPath: /var/cache/nginx  
  volumes:
    - name: nginx-cache
      persistentVolumeClaim:
        claimName: claim-cache-ebs

